/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aispeech_player_Demo */

#ifndef _Included_com_aispeech_player_Demo
#define _Included_com_aispeech_player_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aispeech_player_Demo
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aispeech_player_Demo_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
